[package]
name = "ajedrez"
version = "0.1.0"
edition = "2021"
[lib]
name = "ej_ind_ajedrez"
path = "src/lib.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]